# Generated by Django 6.0.3 on 2026-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_coins_customuser_upgrades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='upgrades',
            new_name='reg_stats',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gold_border_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
