# Generated by Django 6.0.3 on 2026-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_upgrades_customuser_reg_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_quiz_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
